In [24]:
import pandas as pd
import numpy as np
import pickle

In [2]:
dfStocks = pd.read_csv('StocksData_9Aug.csv')

In [3]:
dfStocks.loc[dfStocks['buyflag'] > 0, 'buyflag'] = 1
dfStocks.loc[dfStocks['buyflag'] == 0, 'buyflag'] = 0
dfStocks.loc[dfStocks['buyflag'] < 0, 'buyflag'] = -1

In [4]:
dfStocks.columns

Index(['id', 'symbol', 'buyflag', 'sellflag', 'open', 'high', 'low', 'close',
       'last', 'tottrdqty', 'tottrdval', 'timestamp', 'days', 'totaltrades',
       'exchangename', 'priceTrend', 'sma_5', 'sma_13', 'sma_26', 'sma_50',
       'sma_200', 'sma_5c13', 'sma_5c26', 'sma_50c200', 'crossDate5c13',
       'crossDate5c26', 'crossDate50c200', 'macd', 'pp', 'rsiTransitDate',
       'rsi', 'signalval', 'cci', 'cciTransitStatus', 'cciTransitDate',
       'histogram', 'sTransitStatus', 'zTransitStatus', 'sTransitDate',
       'zTransitDate', 'stoch_14k', 'stoch_3d', 'symid', 'exchangeid',
       'avgD50Price', 'avgD50vol', 'avgDPrice', 'avgDvol', 'avgMPrice',
       'avgMvol', 'avgWPrice', 'avgWvol', 'd50pmax', 'd50pmin', 'd50vmax',
       'd50vmin', 'dpmax', 'dpmin', 'dvmax', 'dvmin', 'wpmax', 'wpmin',
       'wvmax', 'wvmin', 'mpmax', 'mpmin', 'mvmax', 'mvmin', 'preClose',
       'preVolume', 'transitdate', 'transitFlag', 'updays5', 'updays20',
       'upperc5', 'upperc20'],
      dtyp

In [5]:
dfStocks['avgMVolRatio'] = dfStocks['tottrdqty']/dfStocks['avgMvol']
dfStocks['avgDVolRatio'] = dfStocks['tottrdqty']/dfStocks['preVolume']
dfStocks['avgWVolRatio'] = dfStocks['tottrdqty']/dfStocks['avgWvol']
dfStocks['avg50DVolRatio'] = dfStocks['tottrdqty']/dfStocks['avgD50vol']
dfStocks['avgMPRatio'] = dfStocks['last']/dfStocks['avgMPrice']
dfStocks['avgDPRatio'] = dfStocks['last']/dfStocks['avgDPrice']
dfStocks['avgWPRatio'] = dfStocks['last']/dfStocks['avgWPrice']
dfStocks['avg50DPRatio'] = dfStocks['last']/dfStocks['avgD50Price']

In [ ]:
dfStocks.hist()

In [22]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_curve, roc_auc_score

In [14]:
#model = RandomForestClassifier(n_estimators=30, max_depth=10, random_state=12345)
model = RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=2, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [15]:
dfStocksTarget = dfStocks['buyflag']
dfStocks.drop(columns=['id', 'symbol', 'buyflag', 'sellflag', 'zTransitDate', 'sTransitDate', 'pp', 'rsiTransitDate', 'transitdate', 'timestamp', 'exchangename', 'exchangeid', 'priceTrend', 'cciTransitDate', 'crossDate5c13', 'crossDate5c26', 'crossDate50c200'], inplace=True)

In [16]:
X_train, X_test, y_train, y_test = train_test_split(dfStocks, dfStocksTarget, test_size=0.33, random_state=123)

In [17]:
model.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=2, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [32]:
dfStocks['Predicted'] = result
dfStocks.to_csv('PredictedCSV')

Signature:
dfStocks.append(
    other,
    ignore_index=False,
    verify_integrity=False,
    sort=None,
)
Docstring:
Append rows of `other` to the end of caller, returning a new object.

Columns in `other` that are not in the caller are added as new columns.

Parameters
----------
other : DataFrame or Series/dict-like object, or list of these
    The data to append.
ignore_index : boolean, default False
    If True, do not use the index labels.
verify_integrity : boolean, default False
    If True, raise ValueError on creating index with duplicates.
sort : boolean, default None
    Sort columns if the columns of `self` and `other` are not aligned.
    The default sorting is deprecated and will change to not-sorting
    in a future version of pandas. Explicitly pass ``sort=True`` to
    silence the warning and sort. Explicitly pass ``sort=False`` to
    silence the warning and not sort.

    .. versionadded:: 0.23.0

Returns
-------
appended : DataFrame

See Also
--------
pandas.conca

In [18]:
y_predict = model.predict(X_test)

In [19]:
roc_curve(y_test, y_predict)

(array([0.        , 0.01121076, 1.        ]),
 array([0.  , 0.05, 1.  ]),
 array([ 2,  1, -1], dtype=int64))

In [25]:
pickle.dump(model, open('RandomForestModel', 'wb'))

In [29]:
loaded_model = pickle.load(open('RandomForestModel', 'rb'))
result = loaded_model.predict(X_test)

In [30]:
result

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1,
       -1, -1, -1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1

In [23]:
roc_auc_score(y_test, y_predict)

0.5193946188340807

In [20]:
y_predict

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1,
       -1, -1, -1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1

In [56]:
y_predict[665]

-1

In [100]:
y_test.iloc[621]

-1

In [85]:
y_predict[107]

1

In [31]:
for i in range(0, result.size):
    if result[i] == 1:
        print(i)

85
107
156
169
173
185
299
318
326
333
365
459
482
564
578
621


In [60]:
y_predict == 1

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,